<?php

namespace Database\Seeders;

use App\Models\AsetPeralatanMesin;
use Illuminate\Database\Seeder;

class AsetSeeder extends Seeder
{
    public function run(): void
    {
        $assets = [
            // Data Awal (3 data)
            [
                'no_reg_pemda'           => 'REG-2024-001',
                'no_reg_kominfo'         => 'KOMINFO-EGOV-001',
                'penanggung_jawab'       => 'Dinas Kominfo',
                'jenis_barang'           => 'Proyektor Epson EB-X400',
                'merek_tipe'             => 'Epson EB-X400',
                'tahun'                  => 2024,
                'harga_perolehan'        => 8500000,
                'no_rangka_seri'         => 'EPSON-X400-8812',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Bidang E-Government',
                'no_sk_bast'             => 'SK/001/KOMINFO/2024',
                'tgl_mulai_pinjam'       => '2026-01-12',
                'tgl_selesai_pinjam'     => '2027-01-12',
            ],
            [
                'no_reg_pemda'           => 'REG-2024-002',
                'no_reg_kominfo'         => 'KOMINFO-UMUM-002',
                'penanggung_jawab'       => 'Bagian Umum',
                'jenis_barang'           => 'Toyota Innova Reborn 2.0 V',
                'merek_tipe'             => 'Toyota Innova',
                'tahun'                  => 2023,
                'harga_perolehan'        => 380000000,
                'no_rangka_seri'         => 'MHFK1111223344',
                'no_mesin'               => '1TR-FE-998822',
                'no_polisi'              => 'DM 1024 AB',
                'no_bpkb'                => 'BPKB-8827361',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Garasi Dinas Kominfo',
                'no_sk_bast'             => 'SK/002/KOMINFO/2024',
                'tgl_mulai_pinjam'       => '2026-02-01',
                'tgl_selesai_pinjam'     => '2026-08-01',
            ],
            [
                'no_reg_pemda'           => 'REG-2024-003',
                'no_reg_kominfo'         => 'KOMINFO-APTIKA-003',
                'penanggung_jawab'       => 'Bidang Aptika',
                'jenis_barang'           => 'Modem Portable Orbit Star H1',
                'merek_tipe'             => 'Telkomsel Orbit H1',
                'tahun'                  => 2024,
                'harga_perolehan'        => 650000,
                'no_rangka_seri'         => 'SN-ORB991823',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Ruang Lab Aptika',
                'no_sk_bast'             => 'SK/003/KOMINFO/2024',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],

            // 20 Data Dummy Baru dengan Kondisi Campuran (Baik, Rusak Ringan, Rusak Berat, Hilang)
            [
                'no_reg_pemda'           => 'REG-2024-004',
                'no_reg_kominfo'         => 'KOMINFO-EGOV-004',
                'penanggung_jawab'       => 'Bidang E-Government',
                'jenis_barang'           => 'Server Rackmount 2U Database',
                'merek_tipe'             => 'Dell PowerEdge R750',
                'tahun'                  => 2023,
                'harga_perolehan'        => 85000000,
                'no_rangka_seri'         => 'DELL-PE-R750-9921',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Ruang Server Diskominfo (NOC)',
                'no_sk_bast'             => 'BAST/004/DISKOMINFO/2023',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-005',
                'no_reg_kominfo'         => 'KOMINFO-APTIKA-005',
                'penanggung_jawab'       => 'Bidang Aptika',
                'jenis_barang'           => 'Switch Core Manageable 48-Port',
                'merek_tipe'             => 'Cisco Catalyst 2960X-48TS',
                'tahun'                  => 2022,
                'harga_perolehan'        => 32500000,
                'no_rangka_seri'         => 'FCW2145L0AB',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Rusak Ringan',
                'keterangan_lokasi_unit' => 'Ruang Server Diskominfo (NOC)',
                'no_sk_bast'             => 'BAST/012/DISKOMINFO/2022',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-006',
                'no_reg_kominfo'         => 'KOMINFO-APTIKA-006',
                'penanggung_jawab'       => 'Bidang Aptika',
                'jenis_barang'           => 'Laptop Operasional Programmer',
                'merek_tipe'             => 'Lenovo ThinkPad T14 Gen 3',
                'tahun'                  => 2024,
                'harga_perolehan'        => 19500000,
                'no_rangka_seri'         => 'PF-39ZK12-LNV',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Ruang Bidang Aptika',
                'no_sk_bast'             => 'SK/006/KOMINFO/2024',
                'tgl_mulai_pinjam'       => '2026-01-05',
                'tgl_selesai_pinjam'     => '2026-12-31',
            ],
            [
                'no_reg_pemda'           => 'REG-2024-007',
                'no_reg_kominfo'         => 'KOMINFO-SEKR-007',
                'penanggung_jawab'       => 'Sekretariat',
                'jenis_barang'           => 'Printer Laserjet Enterprise',
                'merek_tipe'             => 'HP LaserJet Enterprise M608dn',
                'tahun'                  => 2021,
                'harga_perolehan'        => 14200000,
                'no_rangka_seri'         => 'VNB3B08291',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Rusak Ringan',
                'keterangan_lokasi_unit' => 'Bagian Keuangan & Kepegawaian',
                'no_sk_bast'             => 'SK/011/KOMINFO/2021',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-008',
                'no_reg_kominfo'         => 'KOMINFO-EGOV-008',
                'penanggung_jawab'       => 'Bidang E-Government',
                'jenis_barang'           => 'Uninterruptible Power Supply (UPS)',
                'merek_tipe'             => 'APC Smart-UPS RT 5000VA',
                'tahun'                  => 2020,
                'harga_perolehan'        => 28000000,
                'no_rangka_seri'         => 'APC-SURT5000XLI-77',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Rusak Berat',
                'keterangan_lokasi_unit' => 'Ruang Server Diskominfo',
                'no_sk_bast'             => 'SK/015/KOMINFO/2020',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-009',
                'no_reg_kominfo'         => 'KOMINFO-IKP-009',
                'penanggung_jawab'       => 'Bidang Informasi & Komunikasi Publik',
                'jenis_barang'           => 'Drone Pemetaan & Dokumentasi',
                'merek_tipe'             => 'DJI Mavic 3 Enterprise',
                'tahun'                  => 2024,
                'harga_perolehan'        => 45000000,
                'no_rangka_seri'         => '1581F4HKL230009',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Ruang Media Center Diskominfo',
                'no_sk_bast'             => 'BAST/009/DISKOMINFO/2024',
                'tgl_mulai_pinjam'       => '2026-03-01',
                'tgl_selesai_pinjam'     => '2026-09-01',
            ],
            [
                'no_reg_pemda'           => 'REG-2024-010',
                'no_reg_kominfo'         => 'KOMINFO-IKP-010',
                'penanggung_jawab'       => 'Bidang Informasi & Komunikasi Publik',
                'jenis_barang'           => 'Kamera DSLR Profesional Peliputan',
                'merek_tipe'             => 'Canon EOS 90D Kit 18-135mm',
                'tahun'                  => 2023,
                'harga_perolehan'        => 21500000,
                'no_rangka_seri'         => 'CN-90D-8823190',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Ruang Media Center Diskominfo',
                'no_sk_bast'             => 'SK/010/KOMINFO/2023',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-011',
                'no_reg_kominfo'         => 'KOMINFO-UMUM-011',
                'penanggung_jawab'       => 'Bagian Umum',
                'jenis_barang'           => 'Mobil Dinas Operasional Lapangan',
                'merek_tipe'             => 'Toyota Hilux Double Cabin 2.4 G',
                'tahun'                  => 2022,
                'harga_perolehan'        => 425000000,
                'no_rangka_seri'         => 'MHF21A112233990',
                'no_mesin'               => '2GD-FTV-889912',
                'no_polisi'              => 'DM 1088 AB',
                'no_bpkb'                => 'BPKB-9910283',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Garasi Dinas Kominfo',
                'no_sk_bast'             => 'SK/021/KOMINFO/2022',
                'tgl_mulai_pinjam'       => '2026-01-01',
                'tgl_selesai_pinjam'     => '2026-12-31',
            ],
            [
                'no_reg_pemda'           => 'REG-2024-012',
                'no_reg_kominfo'         => 'KOMINFO-APTIKA-012',
                'penanggung_jawab'       => 'Bidang Aptika',
                'jenis_barang'           => 'Sepeda Motor Operasional Jaringan',
                'merek_tipe'             => 'Honda CRF 150L',
                'tahun'                  => 2021,
                'harga_perolehan'        => 35000000,
                'no_rangka_seri'         => 'MH1KD1119KK88102',
                'no_mesin'               => 'KD11E-1234567',
                'no_polisi'              => 'DM 2045 AB',
                'no_bpkb'                => 'BPKB-7719201',
                'kondisi'                => 'Rusak Ringan',
                'keterangan_lokasi_unit' => 'Parkiran Dinas Kominfo',
                'no_sk_bast'             => 'SK/012/KOMINFO/2021',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-013',
                'no_reg_kominfo'         => 'KOMINFO-IKP-013',
                'penanggung_jawab'       => 'Bidang Informasi & Komunikasi Publik',
                'jenis_barang'           => 'PC Workstation Video Editor',
                'merek_tipe'             => 'Asus ROG Strix G15CF Core i7',
                'tahun'                  => 2024,
                'harga_perolehan'        => 27500000,
                'no_rangka_seri'         => 'M5NRCX001928372',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Ruang Peliputan & Berita',
                'no_sk_bast'             => 'BAST/013/DISKOMINFO/2024',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-014',
                'no_reg_kominfo'         => 'KOMINFO-EGOV-014',
                'penanggung_jawab'       => 'Bidang E-Government',
                'jenis_barang'           => 'Access Point Outdoor Tower',
                'merek_tipe'             => 'Ubiquiti UniFi AC Mesh Pro',
                'tahun'                  => 2021,
                'harga_perolehan'        => 3800000,
                'no_rangka_seri'         => 'UBNT-UAP-AC-M-PRO-19',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Rusak Berat',
                'keterangan_lokasi_unit' => 'Tower Pemancar Diskominfo',
                'no_sk_bast'             => 'SK/014/KOMINFO/2021',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-015',
                'no_reg_kominfo'         => 'KOMINFO-IKP-015',
                'penanggung_jawab'       => 'Bidang Informasi & Komunikasi Publik',
                'jenis_barang'           => 'Modem Router Portable Lapangan',
                'merek_tipe'             => 'Huawei E5577 Max 4G LTE',
                'tahun'                  => 2022,
                'harga_perolehan'        => 1200000,
                'no_rangka_seri'         => 'HW-E5577-MAX-0091',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Hilang',
                'keterangan_lokasi_unit' => 'Ruang Peliputan & Berita',
                'no_sk_bast'             => 'SK/015/KOMINFO/2022',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-016',
                'no_reg_kominfo'         => 'KOMINFO-UMUM-016',
                'penanggung_jawab'       => 'Bagian Umum',
                'jenis_barang'           => 'Genset Silent Diesel Portabel',
                'merek_tipe'             => 'Perkins Silent Generator 15 kVA',
                'tahun'                  => 2022,
                'harga_perolehan'        => 98000000,
                'no_rangka_seri'         => 'PRK-GEN-15KVA-0881',
                'no_mesin'               => 'PK-ENG-881920',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Rumah Genset Belakang Kantor',
                'no_sk_bast'             => 'BAST/016/DISKOMINFO/2022',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-017',
                'no_reg_kominfo'         => 'KOMINFO-UMUM-017',
                'penanggung_jawab'       => 'Bagian Umum',
                'jenis_barang'           => 'Proyektor Portabel Ruang Rapat',
                'merek_tipe'             => 'InFocus IN114xv DLP Projector',
                'tahun'                  => 2020,
                'harga_perolehan'        => 5500000,
                'no_rangka_seri'         => 'INF-IN114XV-8819',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Hilang',
                'keterangan_lokasi_unit' => 'Ruang Rapat Wakil Bupati',
                'no_sk_bast'             => 'SK/017/KOMINFO/2020',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-018',
                'no_reg_kominfo'         => 'KOMINFO-SEKR-018',
                'penanggung_jawab'       => 'Sekretariat',
                'jenis_barang'           => 'Mesin Fotocopy Multifungsi A3',
                'merek_tipe'             => 'Fuji Xerox DocuCentre SC2022',
                'tahun'                  => 2021,
                'harga_perolehan'        => 34000000,
                'no_rangka_seri'         => 'FX-SC2022-99120',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Rusak Ringan',
                'keterangan_lokasi_unit' => 'Ruang Tata Usaha & Kearsipan',
                'no_sk_bast'             => 'SK/018/KOMINFO/2021',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-019',
                'no_reg_kominfo'         => 'KOMINFO-EGOV-019',
                'penanggung_jawab'       => 'Bidang E-Government',
                'jenis_barang'           => 'Smart TV Interactive Display 65 Inch',
                'merek_tipe'             => 'Samsung Flip Pro WM65B 4K UHD',
                'tahun'                  => 2024,
                'harga_perolehan'        => 36000000,
                'no_rangka_seri'         => 'SM-WM65B-9988123',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Ruang Command Center Bone Bolango',
                'no_sk_bast'             => 'BAST/019/DISKOMINFO/2024',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-020',
                'no_reg_kominfo'         => 'KOMINFO-STAT-020',
                'penanggung_jawab'       => 'Bidang Statistik & Persandian',
                'jenis_barang'           => 'Network Attached Storage (NAS)',
                'merek_tipe'             => 'Synology DiskStation DS920+ 16TB',
                'tahun'                  => 2023,
                'harga_perolehan'        => 18500000,
                'no_rangka_seri'         => 'SYN-DS920P-16TB-991',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Ruang Server Diskominfo',
                'no_sk_bast'             => 'BAST/020/DISKOMINFO/2023',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-021',
                'no_reg_kominfo'         => 'KOMINFO-STAT-021',
                'penanggung_jawab'       => 'Bidang Statistik & Persandian',
                'jenis_barang'           => 'Handy Talky (HT) Digital Persandian',
                'merek_tipe'             => 'Motorola XiR P6620i TIA VHF',
                'tahun'                  => 2019,
                'harga_perolehan'        => 4800000,
                'no_rangka_seri'         => 'MOT-P6620I-881920',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Rusak Berat',
                'keterangan_lokasi_unit' => 'Gudang Inventaris Diskominfo',
                'no_sk_bast'             => 'SK/021/KOMINFO/2019',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-022',
                'no_reg_kominfo'         => 'KOMINFO-APTIKA-022',
                'penanggung_jawab'       => 'Bidang Aptika',
                'jenis_barang'           => 'Hardisk Eksternal Backup Data 4TB',
                'merek_tipe'             => 'Seagate One Touch 4TB USB 3.0',
                'tahun'                  => 2022,
                'harga_perolehan'        => 1950000,
                'no_rangka_seri'         => 'NA9M1902K',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Hilang',
                'keterangan_lokasi_unit' => 'Ruang Layanan Aptika',
                'no_sk_bast'             => 'SK/022/KOMINFO/2022',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
            [
                'no_reg_pemda'           => 'REG-2024-023',
                'no_reg_kominfo'         => 'KOMINFO-UMUM-023',
                'penanggung_jawab'       => 'Bagian Umum',
                'jenis_barang'           => 'Mesin Absensi Face Recognition',
                'merek_tipe'             => 'Solution Face X601 Biometrik',
                'tahun'                  => 2023,
                'harga_perolehan'        => 4750000,
                'no_rangka_seri'         => 'SOL-X601-2023-8812',
                'no_mesin'               => '-',
                'no_polisi'              => '-',
                'no_bpkb'                => '-',
                'kondisi'                => 'Baik',
                'keterangan_lokasi_unit' => 'Lobby Utama Diskominfo',
                'no_sk_bast'             => 'BAST/023/DISKOMINFO/2023',
                'tgl_mulai_pinjam'       => null,
                'tgl_selesai_pinjam'     => null,
            ],
        ];

        foreach ($assets as $asset) {
            AsetPeralatanMesin::updateOrCreate(
                ['no_reg_pemda' => $asset['no_reg_pemda']],
                $asset
            );
        }
    }
}
